//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagensIndustri.Templates.Public.Units.Placeable.DiCampaign {
    
    
    public partial class CampaignCodeForm {
        
        /// <summary>
        /// CodeInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CodeInput;
        
        /// <summary>
        /// CodeFormButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CodeFormButton;
    }
}
