//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagensIndustri.Templates.Public.Pages.DiCampaign {
    
    
    public partial class Campaign {
        
        /// <summary>
        /// LabelErr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelErr;
        
        /// <summary>
        /// MainFormPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder MainFormPlaceHolder;
        
        /// <summary>
        /// CampForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Templates.Public.Units.Placeable.DiCampaign.CampaignForm CampForm;
        
        /// <summary>
        /// OtherPayerPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder OtherPayerPlaceHolder;
        
        /// <summary>
        /// OtherPayerForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Templates.Public.Units.Placeable.DiCampaign.CampaignOtherPayerForm OtherPayerForm;
        
        /// <summary>
        /// ThankYouPlaceholder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder ThankYouPlaceholder;
        
        /// <summary>
        /// CampThankYou control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Templates.Public.Units.Placeable.DiCampaign.CampaignThankYou CampThankYou;
        
        /// <summary>
        /// LiteralAdWordsScriptOnLoad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal LiteralAdWordsScriptOnLoad;
        
        /// <summary>
        /// LiteralAdWordsScriptOnThankYou control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal LiteralAdWordsScriptOnThankYou;
    }
}
