//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagensIndustri.Templates.Public.Pages.Conference {
    
    
    public partial class ConferencePerson {
        
        /// <summary>
        /// HeadingControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Templates.Public.Units.Placeable.Heading HeadingControl;
        
        /// <summary>
        /// phDisableAllInputs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phDisableAllInputs;
        
        /// <summary>
        /// UserMessageControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Templates.Public.Units.Placeable.UserMessage UserMessageControl;
        
        /// <summary>
        /// PlaceHolderConferenceUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder PlaceHolderConferenceUpdate;
        
        /// <summary>
        /// FirstNameInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation FirstNameInput;
        
        /// <summary>
        /// LastNameInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation LastNameInput;
        
        /// <summary>
        /// CompanyInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CompanyInput;
        
        /// <summary>
        /// TitleInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation TitleInput;
        
        /// <summary>
        /// OrgNumberInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation OrgNumberInput;
        
        /// <summary>
        /// TelephoneInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation TelephoneInput;
        
        /// <summary>
        /// EmailInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation EmailInput;
        
        /// <summary>
        /// InvoiceAddressInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation InvoiceAddressInput;
        
        /// <summary>
        /// InvoiceReferenceInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation InvoiceReferenceInput;
        
        /// <summary>
        /// ZipCodeInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation ZipCodeInput;
        
        /// <summary>
        /// StateInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation StateInput;
        
        /// <summary>
        /// ConferenceRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater ConferenceRepeater;
        
        /// <summary>
        /// ConferenceUpdateButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ConferenceUpdateButton;
    }
}
