//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pren.Web.AutowithdrawalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.dagensindustri.se/", ConfigurationName="AutowithdrawalService.AutowithdrawalSoap")]
    public interface AutowithdrawalSoap {
        
        // CODEGEN: Generating message contract since element name accessToken from namespace http://ws.dagensindustri.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dagensindustri.se/InsertAutoWithdrawal", ReplyAction="*")]
        Pren.Web.AutowithdrawalService.InsertAutoWithdrawalResponse InsertAutoWithdrawal(Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dagensindustri.se/InsertAutoWithdrawal", ReplyAction="*")]
        System.Threading.Tasks.Task<Pren.Web.AutowithdrawalService.InsertAutoWithdrawalResponse> InsertAutoWithdrawalAsync(Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAutoWithdrawalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAutoWithdrawal", Namespace="http://ws.dagensindustri.se/", Order=0)]
        public Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequestBody Body;
        
        public InsertAutoWithdrawalRequest() {
        }
        
        public InsertAutoWithdrawalRequest(Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.dagensindustri.se/")]
    public partial class InsertAutoWithdrawalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accessToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string aurigaSubsId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long cusno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long subsno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long campno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int includeInBatch;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pageGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> subsEndDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime dateSaved;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<System.DateTime> dateStopped;
        
        public InsertAutoWithdrawalRequestBody() {
        }
        
        public InsertAutoWithdrawalRequestBody(string accessToken, string aurigaSubsId, long cusno, long subsno, long campno, int includeInBatch, string pageGuid, System.Nullable<System.DateTime> subsEndDate, System.DateTime dateSaved, System.Nullable<System.DateTime> dateStopped) {
            this.accessToken = accessToken;
            this.aurigaSubsId = aurigaSubsId;
            this.cusno = cusno;
            this.subsno = subsno;
            this.campno = campno;
            this.includeInBatch = includeInBatch;
            this.pageGuid = pageGuid;
            this.subsEndDate = subsEndDate;
            this.dateSaved = dateSaved;
            this.dateStopped = dateStopped;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAutoWithdrawalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAutoWithdrawalResponse", Namespace="http://ws.dagensindustri.se/", Order=0)]
        public Pren.Web.AutowithdrawalService.InsertAutoWithdrawalResponseBody Body;
        
        public InsertAutoWithdrawalResponse() {
        }
        
        public InsertAutoWithdrawalResponse(Pren.Web.AutowithdrawalService.InsertAutoWithdrawalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.dagensindustri.se/")]
    public partial class InsertAutoWithdrawalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertAutoWithdrawalResult;
        
        public InsertAutoWithdrawalResponseBody() {
        }
        
        public InsertAutoWithdrawalResponseBody(bool InsertAutoWithdrawalResult) {
            this.InsertAutoWithdrawalResult = InsertAutoWithdrawalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutowithdrawalSoapChannel : Pren.Web.AutowithdrawalService.AutowithdrawalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutowithdrawalSoapClient : System.ServiceModel.ClientBase<Pren.Web.AutowithdrawalService.AutowithdrawalSoap>, Pren.Web.AutowithdrawalService.AutowithdrawalSoap {
        
        public AutowithdrawalSoapClient() {
        }
        
        public AutowithdrawalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutowithdrawalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutowithdrawalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutowithdrawalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pren.Web.AutowithdrawalService.InsertAutoWithdrawalResponse Pren.Web.AutowithdrawalService.AutowithdrawalSoap.InsertAutoWithdrawal(Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequest request) {
            return base.Channel.InsertAutoWithdrawal(request);
        }
        
        public bool InsertAutoWithdrawal(string accessToken, string aurigaSubsId, long cusno, long subsno, long campno, int includeInBatch, string pageGuid, System.Nullable<System.DateTime> subsEndDate, System.DateTime dateSaved, System.Nullable<System.DateTime> dateStopped) {
            Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequest inValue = new Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequest();
            inValue.Body = new Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.aurigaSubsId = aurigaSubsId;
            inValue.Body.cusno = cusno;
            inValue.Body.subsno = subsno;
            inValue.Body.campno = campno;
            inValue.Body.includeInBatch = includeInBatch;
            inValue.Body.pageGuid = pageGuid;
            inValue.Body.subsEndDate = subsEndDate;
            inValue.Body.dateSaved = dateSaved;
            inValue.Body.dateStopped = dateStopped;
            Pren.Web.AutowithdrawalService.InsertAutoWithdrawalResponse retVal = ((Pren.Web.AutowithdrawalService.AutowithdrawalSoap)(this)).InsertAutoWithdrawal(inValue);
            return retVal.Body.InsertAutoWithdrawalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pren.Web.AutowithdrawalService.InsertAutoWithdrawalResponse> Pren.Web.AutowithdrawalService.AutowithdrawalSoap.InsertAutoWithdrawalAsync(Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequest request) {
            return base.Channel.InsertAutoWithdrawalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pren.Web.AutowithdrawalService.InsertAutoWithdrawalResponse> InsertAutoWithdrawalAsync(string accessToken, string aurigaSubsId, long cusno, long subsno, long campno, int includeInBatch, string pageGuid, System.Nullable<System.DateTime> subsEndDate, System.DateTime dateSaved, System.Nullable<System.DateTime> dateStopped) {
            Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequest inValue = new Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequest();
            inValue.Body = new Pren.Web.AutowithdrawalService.InsertAutoWithdrawalRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.aurigaSubsId = aurigaSubsId;
            inValue.Body.cusno = cusno;
            inValue.Body.subsno = subsno;
            inValue.Body.campno = campno;
            inValue.Body.includeInBatch = includeInBatch;
            inValue.Body.pageGuid = pageGuid;
            inValue.Body.subsEndDate = subsEndDate;
            inValue.Body.dateSaved = dateSaved;
            inValue.Body.dateStopped = dateStopped;
            return ((Pren.Web.AutowithdrawalService.AutowithdrawalSoap)(this)).InsertAutoWithdrawalAsync(inValue);
        }
    }
}
