//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pren.Web.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodePortalCode
    {
        public CodePortalCode()
        {
            this.CodePortalGiveAway = new HashSet<CodePortalGiveAway>();
        }
    
        public int Id { get; set; }
        public int fkListId { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public string UsedById { get; set; }
        public string UsedByEmail { get; set; }
    
        public virtual CodePortalList CodePortalList { get; set; }
        public virtual ICollection<CodePortalGiveAway> CodePortalGiveAway { get; set; }
    }
}
