//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pren.Web.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTable
    {
        public int id { get; set; }
        public string errorFileName { get; set; }
        public string description { get; set; }
        public string exception { get; set; }
        public System.DateTime date { get; set; }
    }
}
