//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIClassLib.ApsisWs_v3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Apsis Newsletter Pro v3 APISoap", Namespace="http://api.anpdm.com/", ConfigurationName="ApsisWs_v3.ApsisNewsletterProv3APISoap")]
    public interface ApsisNewsletterProv3APISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/DeleteSubscription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteSubscription(string strUsername, string strPassword, string strSubscriberID, string strEmail, string strMailingListID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertSubscription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long InsertSubscription(string strUsername, string strPassword, string strSubscriberID, string strEmail, int strMailingListID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertTransaction(string strUsername, string strPassword, string strId, string strIdentifier, string strEmail, string strName, string strFormat, string strSendTime, string strDataFields, string strDataValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertTransactionWithSplit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertTransactionWithSplit(string strUsername, string strPassword, string strId, string strIdentifier, string strEmail, string strName, string strFormat, string strSendTime, string strDataFields, string strDataValues);
        
        // CODEGEN: Parameter 'InsertTransactionFromFileResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertTransactionFromFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.InsertTransactionFromFileResponse InsertTransactionFromFile(DIClassLib.ApsisWs_v3.InsertTransactionFromFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetTransactionProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTransactionProjects(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetTransactionDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTransactionDetails(string strUsername, string strPassword, string strId, string strIdentifier, string strEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetTransactionBouncesByDateInterval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTransactionBouncesByDateInterval(string strUsername, string strPassword, string strProjectGuid, string datIntervalFrom, string datIntervalTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetLoginLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLoginLink(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetDemographicData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDemographicData(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetRoiResults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.RoiResult[] GetRoiResults(string strUsername, string strPassword, string strSendQueueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/SendSmsToMailingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.SmsMassMessageResult SendSmsToMailingList(string strUsername, string strPassword, string strMailingListId, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.SmsSingleMessageResult SendSms(string strUsername, string strPassword, string strCountryCode, string strPhoneNumber, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/SendSmsWithSenderName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.SmsSingleMessageResult SendSmsWithSenderName(string strUsername, string strPassword, string senderName, string strCountryCode, string strPhoneNumber, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetLinkInfoInExcelFormat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLinkInfoInExcelFormat(string strUsername, string strPassword, string strStartTime, string strEndTime, string strLinkUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetFilters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFilters(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetNewsletterFilters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.NewsletterFilterResult[] GetNewsletterFilters(string strUsername, string strPassword, int intNewsletterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetNewsletterWebVersionUrlByFilters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNewsletterWebVersionUrlByFilters(string strUsername, string strPassword, int intNewsletterId, int[] intFilterIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetTriggerIdForAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.TriggerResult[] GetTriggerIdForAccount(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetTriggerClicks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.TriggerSubscriberClicksResult[] GetTriggerClicks(string strUsername, string strPassword, int triggerId, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetTriggerViews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.TriggerSubscriberViewsResult[] GetTriggerViews(string strUsername, string strPassword, int triggerId, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetTriggerBounces", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.TriggerSubscriberBouncesResult[] GetTriggerBounces(string strUsername, string strPassword, int triggerId, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetOptOutMailing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOptOutMailing(string strUsername, string strPassword, string strSendQueueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetOptOutAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOptOutAll(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetOptOutAllInPeriod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOptOutAllInPeriod(string strUsername, string strPassword, string strFrom, string strTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetOptOutList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOptOutList(string strUsername, string strPassword, string strMailingListId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/DeleteOptOutAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteOptOutAll(string strUsername, string strPassword, string strSubscriberID, string strEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/DeleteOptOutList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteOptOutList(string strUsername, string strPassword, string strSubscriberID, string strEmail, string strMailingListID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/MoveSubscriberToOptOutAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int MoveSubscriberToOptOutAll(string strUsername, string strPassword, string strEmail, string strReason, string strMailinglistId, string strSendQueueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetImporterQueueImportState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetImporterQueueImportState(string strUsername, string strPassword, int intImportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/AddSubscribersFromXmlToQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddSubscribersFromXmlToQueue(string strUsername, string strPassword, int intMailingListId, string strXmlData, bool boolDemographicNameMapping);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertCsvSubscribersFromFileCustom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertCsvSubscribersFromFileCustom(string strUsername, string strPassword, string strMailingListID, string strCSVUrl, char chrDelimiter, char chrQuote, char chrEscape, char chrComment, bool blnHasHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetBounces", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBounces(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long InsertSubscriber(string strUsername, string strPassword, string strEmail, string strName, string strFormat, string strCountryCode, string strPhoneNumber, string strMailingListID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertSubscriberSid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long InsertSubscriberSid(string strUsername, string strPassword, string strEmail, string strName, string strFormat, string strCountryCode, string strPhoneNumber, string strMailingListID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertSubscriberWithDemData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long InsertSubscriberWithDemData(string strUsername, string strPassword, string strMailingListID, string strEmail, string strName, string strCountryCode, string strPhoneNumber, string strFormat, string strDatafields, string strDatavalues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertSubscriberWithDemDataPendingOption", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long InsertSubscriberWithDemDataPendingOption(string strUsername, string strPassword, string strMailingListID, string strEmail, string strName, string strCountryCode, string strPhoneNumber, string strFormat, string strDatafields, string strDatavalues, string strPending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetSubscribers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSubscribers(string strUsername, string strPassword, string strMailingListId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetPagedSubscribers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPagedSubscribers(string strUsername, string strPassword, string strMailingListId, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/DeleteSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteSubscriber(string strUsername, string strPassword, string strEmail, string strMailingListID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetSubscriberDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSubscriberDetails(string strUsername, string strPassword, string strSubscriberId, string strEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertCsvSubscribersWithDemDataUpdateOption", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertCsvSubscribersWithDemDataUpdateOption(string strUsername, string strPassword, string strMailingListId, string strCsvData, string strUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertCsvSubscribersWithDemData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertCsvSubscribersWithDemData(string strUsername, string strPassword, string strMailingListId, string strCsvData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/UpdateSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateSubscriber(string strUsername, string strPassword, string strSubscriberID, string strEmail, string strName, string strFormat, string strCountryCode, string strPhoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/UpdateSubscriberData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateSubscriberData(string strUsername, string strPassword, string strSubscriberId, string strEmail, string strDataField, string strDataValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/UpdateSubscriberEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateSubscriberEmail(string strUsername, string strPassword, string strCurrentEmail, string strNewEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertCSVSubscribersWithDemDataFromFileToQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertCSVSubscribersWithDemDataFromFileToQueue(string strUsername, string strPassword, string strMailingListID, string strCSVUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportActivity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReportActivity(string strUsername, string strPassword, string strSendQueueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReports", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReports(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReportDetails(string strUsername, string strPassword, string sendQueueID, string filterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportViews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReportViews(string strUsername, string strPassword, string strSendQueueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportViewsByDateInterval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReportViewsByDateInterval(string strUsername, string strPassword, string strSendQueueId, string datIntervalFrom, string datIntervalTo, string ddField);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportClicks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReportClicks(string strUsername, string strPassword, string strSendQueueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportClicksByDateInterval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReportClicksByDateInterval(string strUsername, string strPassword, string strSendQueueId, string datIntervalFrom, string datIntervalTo, string ddField);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportBounces", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReportBounces(string strUsername, string strPassword, string strSendQueueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportBouncesByDateInterval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReportBouncesByDateInterval(string strUsername, string strPassword, string strSendQueueId, string datIntervalFrom, string datIntervalTo, string ddField);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetReportLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReportLink(string strUsername, string strPassword, string strSendQueueID, string strNewsletterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetMailingLists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailingLists(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetMailingListDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailingListDetails(string strUsername, string strPassword, string strMailingListId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetSubscriberMailingLists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSubscriberMailingLists(string strUsername, string strPassword, string strSubscriberId, string strEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertMailingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertMailingList(string strUsername, string strPassword, string strListName, string strFromName, string strFromEmail, string strDescription, string strCharacterSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/UpdateMailingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateMailingList(string strUsername, string strPassword, string strMailingListID, string strListName, string strFromName, string strFromEmail, string strDescription, string strCharacterset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/DeleteMailingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteMailingList(string strUsername, string strPassword, string strMailingListId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/MailingListExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int MailingListExists(string strUsername, string strPassword, string strMailingListId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/EmptyMailingListById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EmptyMailingListById(string strUsername, string strPassword, string strMailingListID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetNewsletters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetNewsletters(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetNewsletterDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetNewsletterDetails(string strUsername, string strPassword, string strNewsletterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetSendings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSendings(string strUsername, string strPassword, string strNewsletterId, string strStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertNewsletter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertNewsletter(string strUsername, string strPassword, string strNewsletterName, string strSubject, string strTracking, string strBodyHtml, string strBodyText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/UpdateNewsletter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateNewsletter(string strUsername, string strPassword, string strNewsletterId, string strNewsletterName, string strSubject, string strTracking, string strBodyHtml, string strBodyText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/SendNewsletter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendNewsletter(string strUsername, string strPassword, string strFromEmail, string strFromName, string strNewsletterId, string strMailingListId, string strSendDate, string strSendTime, string strFilterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetSendQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSendQueue(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/UpdateNewsletterEmbedImagesOption", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateNewsletterEmbedImagesOption(string strUsername, string strPassword, string strNewsletterId, bool boolEmbeddedOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/DeleteNewsletter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteNewsletter(string strUsername, string strPassword, string strNewsletterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/DeleteSendqueueItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteSendqueueItem(string strUsername, string strPassword, string strSendQueueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetActiveTemplates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetActiveTemplates(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetTemplates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTemplates(string strUsername, string strPassword);
        
        // CODEGEN: Parameter 'datIntervalFrom' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/GetDetailedNewsletters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DIClassLib.ApsisWs_v3.GetDetailedNewslettersResponse GetDetailedNewsletters(DIClassLib.ApsisWs_v3.GetDetailedNewslettersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertTemplateNewsletter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertTemplateNewsletter(string strUsername, string strPassword, string strTemplateName, string strNewsletterName, string strSubject, string strTracking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/InsertActiveTemplateModule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertActiveTemplateModule(string strUsername, string strPassword, string strNewsletterID, string strModuleID, string strModuleCode, string strModuleIndex, string strFilterID, string strHolderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.anpdm.com/SaveNewsletter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SaveNewsletter(string strUsername, string strPassword, string strNewsletterId, string strNewsletterType);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTransactionFromFile", WrapperNamespace="http://api.anpdm.com/", IsWrapped=true)]
    public partial class InsertTransactionFromFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=0)]
        public string strUsername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=1)]
        public string strPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=2)]
        public string strProjectGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=3)]
        public string strFileUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=4)]
        public string strFormat;
        
        public InsertTransactionFromFileRequest() {
        }
        
        public InsertTransactionFromFileRequest(string strUsername, string strPassword, string strProjectGuid, string strFileUrl, string strFormat) {
            this.strUsername = strUsername;
            this.strPassword = strPassword;
            this.strProjectGuid = strProjectGuid;
            this.strFileUrl = strFileUrl;
            this.strFormat = strFormat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTransactionFromFileResponse", WrapperNamespace="http://api.anpdm.com/", IsWrapped=true)]
    public partial class InsertTransactionFromFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> InsertTransactionFromFileResult;
        
        public InsertTransactionFromFileResponse() {
        }
        
        public InsertTransactionFromFileResponse(System.Nullable<System.Guid> InsertTransactionFromFileResult) {
            this.InsertTransactionFromFileResult = InsertTransactionFromFileResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class RoiResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string urlField;
        
        private int clicksField;
        
        private int closuresField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Clicks {
            get {
                return this.clicksField;
            }
            set {
                this.clicksField = value;
                this.RaisePropertyChanged("Clicks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Closures {
            get {
                return this.closuresField;
            }
            set {
                this.closuresField = value;
                this.RaisePropertyChanged("Closures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class DetailedNewsletterResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string subjectField;
        
        private System.DateTime updatedField;
        
        private System.DateTime createdField;
        
        private bool hasNewsletterBeenSentField;
        
        private int hasNewsletterBeenSentIntegralField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("Updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool HasNewsletterBeenSent {
            get {
                return this.hasNewsletterBeenSentField;
            }
            set {
                this.hasNewsletterBeenSentField = value;
                this.RaisePropertyChanged("HasNewsletterBeenSent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int HasNewsletterBeenSentIntegral {
            get {
                return this.hasNewsletterBeenSentIntegralField;
            }
            set {
                this.hasNewsletterBeenSentIntegralField = value;
                this.RaisePropertyChanged("HasNewsletterBeenSentIntegral");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class TriggerSubscriberBouncesResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string reasonField;
        
        private string emailField;
        
        private string nameField;
        
        private System.DateTime bounceTimeField;
        
        private string newsletterNameField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime BounceTime {
            get {
                return this.bounceTimeField;
            }
            set {
                this.bounceTimeField = value;
                this.RaisePropertyChanged("BounceTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NewsletterName {
            get {
                return this.newsletterNameField;
            }
            set {
                this.newsletterNameField = value;
                this.RaisePropertyChanged("NewsletterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class TriggerSubscriberViewsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string nameField;
        
        private System.DateTime viewTimeField;
        
        private string newsletterNameField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ViewTime {
            get {
                return this.viewTimeField;
            }
            set {
                this.viewTimeField = value;
                this.RaisePropertyChanged("ViewTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NewsletterName {
            get {
                return this.newsletterNameField;
            }
            set {
                this.newsletterNameField = value;
                this.RaisePropertyChanged("NewsletterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class TriggerSubscriberClicksResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string linkField;
        
        private string emailField;
        
        private string nameField;
        
        private System.DateTime clickTimeField;
        
        private string newsletterNameField;
        
        private string subscriberIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("Link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ClickTime {
            get {
                return this.clickTimeField;
            }
            set {
                this.clickTimeField = value;
                this.RaisePropertyChanged("ClickTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NewsletterName {
            get {
                return this.newsletterNameField;
            }
            set {
                this.newsletterNameField = value;
                this.RaisePropertyChanged("NewsletterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class TriggerResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private System.DateTime createdField;
        
        private int mailinglistIdField;
        
        private string mailinglistNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int MailinglistId {
            get {
                return this.mailinglistIdField;
            }
            set {
                this.mailinglistIdField = value;
                this.RaisePropertyChanged("MailinglistId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MailinglistName {
            get {
                return this.mailinglistNameField;
            }
            set {
                this.mailinglistNameField = value;
                this.RaisePropertyChanged("MailinglistName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class NewsletterFilterResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class SmsSingleMessageResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private short creditCostField;
        
        private int totalCreditsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short CreditCost {
            get {
                return this.creditCostField;
            }
            set {
                this.creditCostField = value;
                this.RaisePropertyChanged("CreditCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TotalCredits {
            get {
                return this.totalCreditsField;
            }
            set {
                this.totalCreditsField = value;
                this.RaisePropertyChanged("TotalCredits");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.anpdm.com/")]
    public partial class SmsMassMessageResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short creditCostField;
        
        private int totalCreditsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short CreditCost {
            get {
                return this.creditCostField;
            }
            set {
                this.creditCostField = value;
                this.RaisePropertyChanged("CreditCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalCredits {
            get {
                return this.totalCreditsField;
            }
            set {
                this.totalCreditsField = value;
                this.RaisePropertyChanged("TotalCredits");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetailedNewsletters", WrapperNamespace="http://api.anpdm.com/", IsWrapped=true)]
    public partial class GetDetailedNewslettersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=0)]
        public string strUsername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=1)]
        public string strPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> datIntervalFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> datIntervalTo;
        
        public GetDetailedNewslettersRequest() {
        }
        
        public GetDetailedNewslettersRequest(string strUsername, string strPassword, System.Nullable<System.DateTime> datIntervalFrom, System.Nullable<System.DateTime> datIntervalTo) {
            this.strUsername = strUsername;
            this.strPassword = strPassword;
            this.datIntervalFrom = datIntervalFrom;
            this.datIntervalTo = datIntervalTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetailedNewslettersResponse", WrapperNamespace="http://api.anpdm.com/", IsWrapped=true)]
    public partial class GetDetailedNewslettersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.anpdm.com/", Order=0)]
        public DIClassLib.ApsisWs_v3.DetailedNewsletterResult[] GetDetailedNewslettersResult;
        
        public GetDetailedNewslettersResponse() {
        }
        
        public GetDetailedNewslettersResponse(DIClassLib.ApsisWs_v3.DetailedNewsletterResult[] GetDetailedNewslettersResult) {
            this.GetDetailedNewslettersResult = GetDetailedNewslettersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApsisNewsletterProv3APISoapChannel : DIClassLib.ApsisWs_v3.ApsisNewsletterProv3APISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApsisNewsletterProv3APISoapClient : System.ServiceModel.ClientBase<DIClassLib.ApsisWs_v3.ApsisNewsletterProv3APISoap>, DIClassLib.ApsisWs_v3.ApsisNewsletterProv3APISoap {
        
        public ApsisNewsletterProv3APISoapClient() {
        }
        
        public ApsisNewsletterProv3APISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApsisNewsletterProv3APISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApsisNewsletterProv3APISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApsisNewsletterProv3APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DeleteSubscription(string strUsername, string strPassword, string strSubscriberID, string strEmail, string strMailingListID) {
            return base.Channel.DeleteSubscription(strUsername, strPassword, strSubscriberID, strEmail, strMailingListID);
        }
        
        public long InsertSubscription(string strUsername, string strPassword, string strSubscriberID, string strEmail, int strMailingListID) {
            return base.Channel.InsertSubscription(strUsername, strPassword, strSubscriberID, strEmail, strMailingListID);
        }
        
        public int InsertTransaction(string strUsername, string strPassword, string strId, string strIdentifier, string strEmail, string strName, string strFormat, string strSendTime, string strDataFields, string strDataValues) {
            return base.Channel.InsertTransaction(strUsername, strPassword, strId, strIdentifier, strEmail, strName, strFormat, strSendTime, strDataFields, strDataValues);
        }
        
        public int InsertTransactionWithSplit(string strUsername, string strPassword, string strId, string strIdentifier, string strEmail, string strName, string strFormat, string strSendTime, string strDataFields, string strDataValues) {
            return base.Channel.InsertTransactionWithSplit(strUsername, strPassword, strId, strIdentifier, strEmail, strName, strFormat, strSendTime, strDataFields, strDataValues);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DIClassLib.ApsisWs_v3.InsertTransactionFromFileResponse DIClassLib.ApsisWs_v3.ApsisNewsletterProv3APISoap.InsertTransactionFromFile(DIClassLib.ApsisWs_v3.InsertTransactionFromFileRequest request) {
            return base.Channel.InsertTransactionFromFile(request);
        }
        
        public System.Nullable<System.Guid> InsertTransactionFromFile(string strUsername, string strPassword, string strProjectGuid, string strFileUrl, string strFormat) {
            DIClassLib.ApsisWs_v3.InsertTransactionFromFileRequest inValue = new DIClassLib.ApsisWs_v3.InsertTransactionFromFileRequest();
            inValue.strUsername = strUsername;
            inValue.strPassword = strPassword;
            inValue.strProjectGuid = strProjectGuid;
            inValue.strFileUrl = strFileUrl;
            inValue.strFormat = strFormat;
            DIClassLib.ApsisWs_v3.InsertTransactionFromFileResponse retVal = ((DIClassLib.ApsisWs_v3.ApsisNewsletterProv3APISoap)(this)).InsertTransactionFromFile(inValue);
            return retVal.InsertTransactionFromFileResult;
        }
        
        public System.Data.DataSet GetTransactionProjects(string strUsername, string strPassword) {
            return base.Channel.GetTransactionProjects(strUsername, strPassword);
        }
        
        public System.Data.DataSet GetTransactionDetails(string strUsername, string strPassword, string strId, string strIdentifier, string strEmail) {
            return base.Channel.GetTransactionDetails(strUsername, strPassword, strId, strIdentifier, strEmail);
        }
        
        public System.Data.DataSet GetTransactionBouncesByDateInterval(string strUsername, string strPassword, string strProjectGuid, string datIntervalFrom, string datIntervalTo) {
            return base.Channel.GetTransactionBouncesByDateInterval(strUsername, strPassword, strProjectGuid, datIntervalFrom, datIntervalTo);
        }
        
        public string GetLoginLink(string strUsername, string strPassword) {
            return base.Channel.GetLoginLink(strUsername, strPassword);
        }
        
        public System.Data.DataSet GetDemographicData(string strUsername, string strPassword) {
            return base.Channel.GetDemographicData(strUsername, strPassword);
        }
        
        public DIClassLib.ApsisWs_v3.RoiResult[] GetRoiResults(string strUsername, string strPassword, string strSendQueueId) {
            return base.Channel.GetRoiResults(strUsername, strPassword, strSendQueueId);
        }
        
        public DIClassLib.ApsisWs_v3.SmsMassMessageResult SendSmsToMailingList(string strUsername, string strPassword, string strMailingListId, string strMessage) {
            return base.Channel.SendSmsToMailingList(strUsername, strPassword, strMailingListId, strMessage);
        }
        
        public DIClassLib.ApsisWs_v3.SmsSingleMessageResult SendSms(string strUsername, string strPassword, string strCountryCode, string strPhoneNumber, string strMessage) {
            return base.Channel.SendSms(strUsername, strPassword, strCountryCode, strPhoneNumber, strMessage);
        }
        
        public DIClassLib.ApsisWs_v3.SmsSingleMessageResult SendSmsWithSenderName(string strUsername, string strPassword, string senderName, string strCountryCode, string strPhoneNumber, string strMessage) {
            return base.Channel.SendSmsWithSenderName(strUsername, strPassword, senderName, strCountryCode, strPhoneNumber, strMessage);
        }
        
        public System.Data.DataSet GetLinkInfoInExcelFormat(string strUsername, string strPassword, string strStartTime, string strEndTime, string strLinkUrl) {
            return base.Channel.GetLinkInfoInExcelFormat(strUsername, strPassword, strStartTime, strEndTime, strLinkUrl);
        }
        
        public System.Data.DataSet GetFilters(string strUsername, string strPassword) {
            return base.Channel.GetFilters(strUsername, strPassword);
        }
        
        public DIClassLib.ApsisWs_v3.NewsletterFilterResult[] GetNewsletterFilters(string strUsername, string strPassword, int intNewsletterId) {
            return base.Channel.GetNewsletterFilters(strUsername, strPassword, intNewsletterId);
        }
        
        public string GetNewsletterWebVersionUrlByFilters(string strUsername, string strPassword, int intNewsletterId, int[] intFilterIds) {
            return base.Channel.GetNewsletterWebVersionUrlByFilters(strUsername, strPassword, intNewsletterId, intFilterIds);
        }
        
        public DIClassLib.ApsisWs_v3.TriggerResult[] GetTriggerIdForAccount(string strUsername, string strPassword) {
            return base.Channel.GetTriggerIdForAccount(strUsername, strPassword);
        }
        
        public DIClassLib.ApsisWs_v3.TriggerSubscriberClicksResult[] GetTriggerClicks(string strUsername, string strPassword, int triggerId, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetTriggerClicks(strUsername, strPassword, triggerId, fromDate, toDate);
        }
        
        public DIClassLib.ApsisWs_v3.TriggerSubscriberViewsResult[] GetTriggerViews(string strUsername, string strPassword, int triggerId, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetTriggerViews(strUsername, strPassword, triggerId, fromDate, toDate);
        }
        
        public DIClassLib.ApsisWs_v3.TriggerSubscriberBouncesResult[] GetTriggerBounces(string strUsername, string strPassword, int triggerId, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetTriggerBounces(strUsername, strPassword, triggerId, fromDate, toDate);
        }
        
        public System.Data.DataSet GetOptOutMailing(string strUsername, string strPassword, string strSendQueueID) {
            return base.Channel.GetOptOutMailing(strUsername, strPassword, strSendQueueID);
        }
        
        public System.Data.DataSet GetOptOutAll(string strUsername, string strPassword) {
            return base.Channel.GetOptOutAll(strUsername, strPassword);
        }
        
        public System.Data.DataSet GetOptOutAllInPeriod(string strUsername, string strPassword, string strFrom, string strTo) {
            return base.Channel.GetOptOutAllInPeriod(strUsername, strPassword, strFrom, strTo);
        }
        
        public System.Data.DataSet GetOptOutList(string strUsername, string strPassword, string strMailingListId) {
            return base.Channel.GetOptOutList(strUsername, strPassword, strMailingListId);
        }
        
        public int DeleteOptOutAll(string strUsername, string strPassword, string strSubscriberID, string strEmail) {
            return base.Channel.DeleteOptOutAll(strUsername, strPassword, strSubscriberID, strEmail);
        }
        
        public int DeleteOptOutList(string strUsername, string strPassword, string strSubscriberID, string strEmail, string strMailingListID) {
            return base.Channel.DeleteOptOutList(strUsername, strPassword, strSubscriberID, strEmail, strMailingListID);
        }
        
        public int MoveSubscriberToOptOutAll(string strUsername, string strPassword, string strEmail, string strReason, string strMailinglistId, string strSendQueueId) {
            return base.Channel.MoveSubscriberToOptOutAll(strUsername, strPassword, strEmail, strReason, strMailinglistId, strSendQueueId);
        }
        
        public int GetImporterQueueImportState(string strUsername, string strPassword, int intImportId) {
            return base.Channel.GetImporterQueueImportState(strUsername, strPassword, intImportId);
        }
        
        public int AddSubscribersFromXmlToQueue(string strUsername, string strPassword, int intMailingListId, string strXmlData, bool boolDemographicNameMapping) {
            return base.Channel.AddSubscribersFromXmlToQueue(strUsername, strPassword, intMailingListId, strXmlData, boolDemographicNameMapping);
        }
        
        public int InsertCsvSubscribersFromFileCustom(string strUsername, string strPassword, string strMailingListID, string strCSVUrl, char chrDelimiter, char chrQuote, char chrEscape, char chrComment, bool blnHasHeaders) {
            return base.Channel.InsertCsvSubscribersFromFileCustom(strUsername, strPassword, strMailingListID, strCSVUrl, chrDelimiter, chrQuote, chrEscape, chrComment, blnHasHeaders);
        }
        
        public System.Data.DataSet GetBounces(string strUsername, string strPassword) {
            return base.Channel.GetBounces(strUsername, strPassword);
        }
        
        public long InsertSubscriber(string strUsername, string strPassword, string strEmail, string strName, string strFormat, string strCountryCode, string strPhoneNumber, string strMailingListID) {
            return base.Channel.InsertSubscriber(strUsername, strPassword, strEmail, strName, strFormat, strCountryCode, strPhoneNumber, strMailingListID);
        }
        
        public long InsertSubscriberSid(string strUsername, string strPassword, string strEmail, string strName, string strFormat, string strCountryCode, string strPhoneNumber, string strMailingListID) {
            return base.Channel.InsertSubscriberSid(strUsername, strPassword, strEmail, strName, strFormat, strCountryCode, strPhoneNumber, strMailingListID);
        }
        
        public long InsertSubscriberWithDemData(string strUsername, string strPassword, string strMailingListID, string strEmail, string strName, string strCountryCode, string strPhoneNumber, string strFormat, string strDatafields, string strDatavalues) {
            return base.Channel.InsertSubscriberWithDemData(strUsername, strPassword, strMailingListID, strEmail, strName, strCountryCode, strPhoneNumber, strFormat, strDatafields, strDatavalues);
        }
        
        public long InsertSubscriberWithDemDataPendingOption(string strUsername, string strPassword, string strMailingListID, string strEmail, string strName, string strCountryCode, string strPhoneNumber, string strFormat, string strDatafields, string strDatavalues, string strPending) {
            return base.Channel.InsertSubscriberWithDemDataPendingOption(strUsername, strPassword, strMailingListID, strEmail, strName, strCountryCode, strPhoneNumber, strFormat, strDatafields, strDatavalues, strPending);
        }
        
        public System.Data.DataSet GetSubscribers(string strUsername, string strPassword, string strMailingListId) {
            return base.Channel.GetSubscribers(strUsername, strPassword, strMailingListId);
        }
        
        public System.Data.DataSet GetPagedSubscribers(string strUsername, string strPassword, string strMailingListId, int pageIndex, int pageSize) {
            return base.Channel.GetPagedSubscribers(strUsername, strPassword, strMailingListId, pageIndex, pageSize);
        }
        
        public int DeleteSubscriber(string strUsername, string strPassword, string strEmail, string strMailingListID) {
            return base.Channel.DeleteSubscriber(strUsername, strPassword, strEmail, strMailingListID);
        }
        
        public System.Data.DataSet GetSubscriberDetails(string strUsername, string strPassword, string strSubscriberId, string strEmail) {
            return base.Channel.GetSubscriberDetails(strUsername, strPassword, strSubscriberId, strEmail);
        }
        
        public int InsertCsvSubscribersWithDemDataUpdateOption(string strUsername, string strPassword, string strMailingListId, string strCsvData, string strUpdate) {
            return base.Channel.InsertCsvSubscribersWithDemDataUpdateOption(strUsername, strPassword, strMailingListId, strCsvData, strUpdate);
        }
        
        public int InsertCsvSubscribersWithDemData(string strUsername, string strPassword, string strMailingListId, string strCsvData) {
            return base.Channel.InsertCsvSubscribersWithDemData(strUsername, strPassword, strMailingListId, strCsvData);
        }
        
        public int UpdateSubscriber(string strUsername, string strPassword, string strSubscriberID, string strEmail, string strName, string strFormat, string strCountryCode, string strPhoneNumber) {
            return base.Channel.UpdateSubscriber(strUsername, strPassword, strSubscriberID, strEmail, strName, strFormat, strCountryCode, strPhoneNumber);
        }
        
        public int UpdateSubscriberData(string strUsername, string strPassword, string strSubscriberId, string strEmail, string strDataField, string strDataValue) {
            return base.Channel.UpdateSubscriberData(strUsername, strPassword, strSubscriberId, strEmail, strDataField, strDataValue);
        }
        
        public int UpdateSubscriberEmail(string strUsername, string strPassword, string strCurrentEmail, string strNewEmail) {
            return base.Channel.UpdateSubscriberEmail(strUsername, strPassword, strCurrentEmail, strNewEmail);
        }
        
        public int InsertCSVSubscribersWithDemDataFromFileToQueue(string strUsername, string strPassword, string strMailingListID, string strCSVUrl) {
            return base.Channel.InsertCSVSubscribersWithDemDataFromFileToQueue(strUsername, strPassword, strMailingListID, strCSVUrl);
        }
        
        public System.Data.DataSet GetReportActivity(string strUsername, string strPassword, string strSendQueueID) {
            return base.Channel.GetReportActivity(strUsername, strPassword, strSendQueueID);
        }
        
        public System.Data.DataSet GetReports(string strUsername, string strPassword) {
            return base.Channel.GetReports(strUsername, strPassword);
        }
        
        public System.Data.DataSet GetReportDetails(string strUsername, string strPassword, string sendQueueID, string filterID) {
            return base.Channel.GetReportDetails(strUsername, strPassword, sendQueueID, filterID);
        }
        
        public System.Data.DataSet GetReportViews(string strUsername, string strPassword, string strSendQueueId) {
            return base.Channel.GetReportViews(strUsername, strPassword, strSendQueueId);
        }
        
        public System.Data.DataSet GetReportViewsByDateInterval(string strUsername, string strPassword, string strSendQueueId, string datIntervalFrom, string datIntervalTo, string ddField) {
            return base.Channel.GetReportViewsByDateInterval(strUsername, strPassword, strSendQueueId, datIntervalFrom, datIntervalTo, ddField);
        }
        
        public System.Data.DataSet GetReportClicks(string strUsername, string strPassword, string strSendQueueId) {
            return base.Channel.GetReportClicks(strUsername, strPassword, strSendQueueId);
        }
        
        public System.Data.DataSet GetReportClicksByDateInterval(string strUsername, string strPassword, string strSendQueueId, string datIntervalFrom, string datIntervalTo, string ddField) {
            return base.Channel.GetReportClicksByDateInterval(strUsername, strPassword, strSendQueueId, datIntervalFrom, datIntervalTo, ddField);
        }
        
        public System.Data.DataSet GetReportBounces(string strUsername, string strPassword, string strSendQueueId) {
            return base.Channel.GetReportBounces(strUsername, strPassword, strSendQueueId);
        }
        
        public System.Data.DataSet GetReportBouncesByDateInterval(string strUsername, string strPassword, string strSendQueueId, string datIntervalFrom, string datIntervalTo, string ddField) {
            return base.Channel.GetReportBouncesByDateInterval(strUsername, strPassword, strSendQueueId, datIntervalFrom, datIntervalTo, ddField);
        }
        
        public string GetReportLink(string strUsername, string strPassword, string strSendQueueID, string strNewsletterID) {
            return base.Channel.GetReportLink(strUsername, strPassword, strSendQueueID, strNewsletterID);
        }
        
        public System.Data.DataSet GetMailingLists(string strUsername, string strPassword) {
            return base.Channel.GetMailingLists(strUsername, strPassword);
        }
        
        public System.Data.DataSet GetMailingListDetails(string strUsername, string strPassword, string strMailingListId) {
            return base.Channel.GetMailingListDetails(strUsername, strPassword, strMailingListId);
        }
        
        public System.Data.DataSet GetSubscriberMailingLists(string strUsername, string strPassword, string strSubscriberId, string strEmail) {
            return base.Channel.GetSubscriberMailingLists(strUsername, strPassword, strSubscriberId, strEmail);
        }
        
        public int InsertMailingList(string strUsername, string strPassword, string strListName, string strFromName, string strFromEmail, string strDescription, string strCharacterSet) {
            return base.Channel.InsertMailingList(strUsername, strPassword, strListName, strFromName, strFromEmail, strDescription, strCharacterSet);
        }
        
        public int UpdateMailingList(string strUsername, string strPassword, string strMailingListID, string strListName, string strFromName, string strFromEmail, string strDescription, string strCharacterset) {
            return base.Channel.UpdateMailingList(strUsername, strPassword, strMailingListID, strListName, strFromName, strFromEmail, strDescription, strCharacterset);
        }
        
        public int DeleteMailingList(string strUsername, string strPassword, string strMailingListId) {
            return base.Channel.DeleteMailingList(strUsername, strPassword, strMailingListId);
        }
        
        public int MailingListExists(string strUsername, string strPassword, string strMailingListId) {
            return base.Channel.MailingListExists(strUsername, strPassword, strMailingListId);
        }
        
        public int EmptyMailingListById(string strUsername, string strPassword, string strMailingListID) {
            return base.Channel.EmptyMailingListById(strUsername, strPassword, strMailingListID);
        }
        
        public System.Data.DataSet GetNewsletters(string strUsername, string strPassword) {
            return base.Channel.GetNewsletters(strUsername, strPassword);
        }
        
        public System.Data.DataSet GetNewsletterDetails(string strUsername, string strPassword, string strNewsletterId) {
            return base.Channel.GetNewsletterDetails(strUsername, strPassword, strNewsletterId);
        }
        
        public System.Data.DataSet GetSendings(string strUsername, string strPassword, string strNewsletterId, string strStatus) {
            return base.Channel.GetSendings(strUsername, strPassword, strNewsletterId, strStatus);
        }
        
        public int InsertNewsletter(string strUsername, string strPassword, string strNewsletterName, string strSubject, string strTracking, string strBodyHtml, string strBodyText) {
            return base.Channel.InsertNewsletter(strUsername, strPassword, strNewsletterName, strSubject, strTracking, strBodyHtml, strBodyText);
        }
        
        public int UpdateNewsletter(string strUsername, string strPassword, string strNewsletterId, string strNewsletterName, string strSubject, string strTracking, string strBodyHtml, string strBodyText) {
            return base.Channel.UpdateNewsletter(strUsername, strPassword, strNewsletterId, strNewsletterName, strSubject, strTracking, strBodyHtml, strBodyText);
        }
        
        public int SendNewsletter(string strUsername, string strPassword, string strFromEmail, string strFromName, string strNewsletterId, string strMailingListId, string strSendDate, string strSendTime, string strFilterId) {
            return base.Channel.SendNewsletter(strUsername, strPassword, strFromEmail, strFromName, strNewsletterId, strMailingListId, strSendDate, strSendTime, strFilterId);
        }
        
        public System.Data.DataSet GetSendQueue(string strUsername, string strPassword) {
            return base.Channel.GetSendQueue(strUsername, strPassword);
        }
        
        public int UpdateNewsletterEmbedImagesOption(string strUsername, string strPassword, string strNewsletterId, bool boolEmbeddedOn) {
            return base.Channel.UpdateNewsletterEmbedImagesOption(strUsername, strPassword, strNewsletterId, boolEmbeddedOn);
        }
        
        public int DeleteNewsletter(string strUsername, string strPassword, string strNewsletterID) {
            return base.Channel.DeleteNewsletter(strUsername, strPassword, strNewsletterID);
        }
        
        public int DeleteSendqueueItem(string strUsername, string strPassword, string strSendQueueID) {
            return base.Channel.DeleteSendqueueItem(strUsername, strPassword, strSendQueueID);
        }
        
        public System.Data.DataSet GetActiveTemplates(string strUsername, string strPassword) {
            return base.Channel.GetActiveTemplates(strUsername, strPassword);
        }
        
        public System.Data.DataSet GetTemplates(string strUsername, string strPassword) {
            return base.Channel.GetTemplates(strUsername, strPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DIClassLib.ApsisWs_v3.GetDetailedNewslettersResponse DIClassLib.ApsisWs_v3.ApsisNewsletterProv3APISoap.GetDetailedNewsletters(DIClassLib.ApsisWs_v3.GetDetailedNewslettersRequest request) {
            return base.Channel.GetDetailedNewsletters(request);
        }
        
        public DIClassLib.ApsisWs_v3.DetailedNewsletterResult[] GetDetailedNewsletters(string strUsername, string strPassword, System.Nullable<System.DateTime> datIntervalFrom, System.Nullable<System.DateTime> datIntervalTo) {
            DIClassLib.ApsisWs_v3.GetDetailedNewslettersRequest inValue = new DIClassLib.ApsisWs_v3.GetDetailedNewslettersRequest();
            inValue.strUsername = strUsername;
            inValue.strPassword = strPassword;
            inValue.datIntervalFrom = datIntervalFrom;
            inValue.datIntervalTo = datIntervalTo;
            DIClassLib.ApsisWs_v3.GetDetailedNewslettersResponse retVal = ((DIClassLib.ApsisWs_v3.ApsisNewsletterProv3APISoap)(this)).GetDetailedNewsletters(inValue);
            return retVal.GetDetailedNewslettersResult;
        }
        
        public int InsertTemplateNewsletter(string strUsername, string strPassword, string strTemplateName, string strNewsletterName, string strSubject, string strTracking) {
            return base.Channel.InsertTemplateNewsletter(strUsername, strPassword, strTemplateName, strNewsletterName, strSubject, strTracking);
        }
        
        public int InsertActiveTemplateModule(string strUsername, string strPassword, string strNewsletterID, string strModuleID, string strModuleCode, string strModuleIndex, string strFilterID, string strHolderID) {
            return base.Channel.InsertActiveTemplateModule(strUsername, strPassword, strNewsletterID, strModuleID, strModuleCode, strModuleIndex, strFilterID, strHolderID);
        }
        
        public int SaveNewsletter(string strUsername, string strPassword, string strNewsletterId, string strNewsletterType) {
            return base.Channel.SaveNewsletter(strUsername, strPassword, strNewsletterId, strNewsletterType);
        }
    }
}
