//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagensIndustri.Templates.Public.Units.Placeable.CardPayment {
    
    
    public partial class SubscriberAddress {
        
        /// <summary>
        /// CompanyInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CompanyInput;
        
        /// <summary>
        /// CompanyNumberInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CompanyNumberInput;
        
        /// <summary>
        /// StreetAddressInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation StreetAddressInput;
        
        /// <summary>
        /// HouseNoInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation HouseNoInput;
        
        /// <summary>
        /// StairCaseInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation StairCaseInput;
        
        /// <summary>
        /// StairsInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation StairsInput;
        
        /// <summary>
        /// AparmentNoInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation AparmentNoInput;
        
        /// <summary>
        /// ZipCodeInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation ZipCodeInput;
        
        /// <summary>
        /// CityInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CityInput;
        
        /// <summary>
        /// CareOfInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CareOfInput;
    }
}
