//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagensIndustri.Templates.Public.Units.Placeable.CardPayment {
    
    
    public partial class PostalPlace {
        
        /// <summary>
        /// CompanyInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CompanyInput;
        
        /// <summary>
        /// CompanyNumberInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CompanyNumberInput;
        
        /// <summary>
        /// PostalplaceInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation PostalplaceInput;
        
        /// <summary>
        /// PostalPlaceNoInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation PostalPlaceNoInput;
        
        /// <summary>
        /// ZipCodeInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation ZipCodeInput;
        
        /// <summary>
        /// CityInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::DagensIndustri.Tools.Classes.WebControls.InputWithValidation CityInput;
    }
}
