<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UspAdmin.aspx.cs" Inherits="Pren.Web.Tools.Admin.UspAdmin.UspAdmin" %>
<%@ Import Namespace="Pren.Web.Tools.Admin.UspAdmin" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>USP-admin</title>
    
    <style type="text/css">
        .tbltop {border:1px solid #888;}
        .tbltop td{padding:5px;}
        table.info{background-color:#eee;border:1px solid #888;}
        
        .tblresult {width:95%;border:1px solid #888;border-collapse:collapse;margin-top:10px;}
        .tblresult td {border:1px solid #888;padding:5px;}
        .tblresult th {border:1px solid #888;background-color:#eee;font-family:Verdana;font-size:14px;padding:5px;}     
        .tblresult th:first-child{ width: 100px;}     
        .tblresult th:nth-child(2) { display: none;}
        .tblresult td:nth-child(2) { display: none;}
        .tblresult input { width: 90%;}    
    </style>    
    
        

</head>
<body>
    <form id="form1" runat="server">
        
        <div id="MainBodyArea">
            <h1>USP-admin</h1>
            
            <div style="display:none;">
                <asp:TextBox runat="server" ID="TxtUspProduct"></asp:TextBox>
                <asp:Button runat="server" OnClick="BtnAddProduct" Text="Lägg till produkt"/>
            </div>

            
            <asp:DropDownList runat="server" ID="DdlProducts" DataSourceID="GvDataSource" DataTextField="Text" DataValueField="Id" Width="200" AutoPostBack="True" OnSelectedIndexChanged="DdlProducts_OnSelectedIndexChanged"/>            
            <asp:GridView runat="server" AutoGenerateEditButton="True" DataKeyNames="Id" AutoGenerateDeleteButton="True" DataSourceID="GvDataSourceText" ID="GvResult" AutoGenerateColumns="False" CssClass="tblresult" AlternatingRowStyle-CssClass="oddrow">
                <Columns>
                    <asp:BoundField HeaderText="Text" DataField="Id" />
                    <asp:BoundField HeaderText="Text" DataField="Text" />
                </Columns>
            </asp:GridView>


            
            <div>
                <asp:Label runat="server"><p><strong>Lägg till ny text för <%=DdlProducts.SelectedItem.Text %></strong></p></asp:Label>           
                <asp:TextBox runat="server" ID="TxtUspProductItem"></asp:TextBox>
                <asp:Button runat="server" OnClick="BtnAddProductItem" Text="Lägg till"/>
            </div>
            
            <div>
                <h3>Platshållare för ikoner</h3>
                <p>[DIWEEKEND] = <img src="/static/css/img/usplogos/di-weekend.png" /></p>
                <p>[DIDIMENSION] = <img src="/static/css/img/usplogos/di-dimension.png" /></p>
                <p>[DIPLUS] = <img src="/static/css/img/usplogos/di-plus.png" /></p>
                <p>[DIETIDNING] = <img src="/static/css/img/usplogos/di-e-tidning.png" /></p>
                <p>[DN] = <img src="/static/css/img/usplogos/dn.png" /></p>
                <p>[DNDIGITALT] = <img src="/static/css/img/usplogos/dn-digitalt.png" /></p>
                <p>[DNPRIO] = <img src="/static/css/img/usplogos/dn-prio.png" /></p>                
            </div>
            
            <asp:ObjectDataSource runat="server" ID="GvDataSource" TypeName="Pren.Web.Tools.Admin.UspAdmin.UspRepository" SelectMethod="GetUspProducts"></asp:ObjectDataSource>

            <asp:ObjectDataSource runat="server" ID="GvDataSourceText" TypeName="Pren.Web.Tools.Admin.UspAdmin.UspRepository" SelectMethod="GetUspTexts" UpdateMethod="UpdateUspText" DeleteMethod="DeleteUspText">
                <SelectParameters>
                    <asp:ControlParameter ControlID="DdlProducts" Name="productId" PropertyName="SelectedValue" Type="Int16" />                     
                </SelectParameters>  
                <UpdateParameters>
                    <asp:Parameter Name="Id" Type="Int16" />
                    <asp:Parameter Name="Text" Type="String" />
                </UpdateParameters>
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int16" />
                </DeleteParameters>
            </asp:ObjectDataSource>             
	   </div>
        
        <asp:Repeater runat="server" id="repUsedOn">
            <HeaderTemplate>
                <h2>Används på:</h2>
            </HeaderTemplate>
            <ItemTemplate>
                <a target="_blank" href="<%#((UsedOn)Container.DataItem).PageUrl%>"><%#((UsedOn)Container.DataItem).PageName%></a><br/>
                Block: <%#((UsedOn)Container.DataItem).BlockName%><br/><br/>
            </ItemTemplate>
        </asp:Repeater>
    </form>
        <script type="text/javascript" src="/Static/js/lib/jquery-1.11.2.min.js"></script>

    <script type="text/javascript">

        $('div').find('a').filter(':contains("Delete")').on("click", function (event) {
            if (!confirm("Är du säker på att du vill fimpa raden?")) {
                event.preventDefault();
            }
        });


    </script>
</body>
</html>
